config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'token_already_used', to: 'pages#token_already_used'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'relevedecomptes', to: 'chatfuels#relevedecomptes'
      get 'gestioncagnottes', to: 'chatfuels#gestioncagnottes'
      get 'gestiondepargne', to: 'chatfuels#gestiondepargne'
      get 'gestionssr', to: 'chatfuels#gestionssr'
      get 'menuquickreplies', to: 'chatfuels#menuquickreplies'
      get 'redirecttomenu', to: 'chatfuels#redirecttomenu'
      get 'veriftoken', to: 'chatfuels#veriftoken'
      get 'parametres', to: 'chatfuels#parametres'
      get 'gestionpause', to: 'chatfuels#gestionpause'
      resources :leads, only: [:create]
    end
  end

  get 'show_cb', to: 'webviews#show_cb'
  get 'show_cagnotte', to: 'webviews#show_cagnotte'
  get 'ma_depargne', to: 'webviews#ma_depargne'
  get 'ssr_pluie', to: 'webviews#ssr_pluie'
  get 'ssr_cigarette', to: 'webviews#ssr_cigarette'
  get 'ssr_virement', to: 'webviews#ssr_virement'
  get 'associer_ssr', to: 'webviews#associer_ssr'
  get 'pre_created', to: 'pages#pre_created'
  get 'profile', to: 'webviews#profile'
  get 'connected_account', to: 'pages#connected_account'

  namespace :budgea, defaults: { format: :json } do
    post 'synchronized_data', to: 'webhooks#synchronized_data'
    post 'daily_update_data', to: 'webhooks#daily_update_data'
  end


  resources :cagnottes, only: [ :new, :create, :edit, :update, :destroy ]
  resources :epargnes
end

app/controllers/webviews_controller.rb
class WebviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show_cb, :show_cagnotte, :associer_ssr, :ma_depargne, :ssr_pluie, :ssr_cigarette, :ssr_virement, :test, :profile]
  before_action :find_user, only: [:show_cb, :show_cagnotte, :associer_ssr, :ma_depargne, :ssr_pluie, :ssr_cigarette, :ssr_virement, :test, :profile]

  def show_cb
    @cb = CompteBancaire.find(params[:cb_id])
    authorize(@cb)
  end

  def show_cagnotte
    @cagnotte = Cagnotte.find(params[:cagnotte_id])
    authorize(@cagnotte)
  end

  def associer_ssr
    @ssr = SmartSavingRule.all
    authorize(@ssr)
  end

  def ma_depargne
    @user = User.find_by(messenger_id: @user_mi)
    @ssr_user = @user.epargnes
    @ssr = SmartSavingRule.where(nom: "dépargne")
    @depargne = {
      depargne_tranquille: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "intelligent", niveau: "faible"),
      depargne_normal: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "intelligent", niveau: "moyen"),
      depargne_ambitieux: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "intelligent", niveau: "fort"),
      depargne_1euro: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "simple", niveau: "faible"),
      depargne_2euro: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "simple", niveau: "moyen"),
      depargne_5euro: SmartSavingRule.find_by(nom: "dépargne", mecanisme: "simple", niveau: "fort")
    }
    a = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_tranquille].id)
    b = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_normal].id)
    c = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_ambitieux].id)
    d = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_1euro].id)
    e = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_2euro].id)
    f = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @depargne[:depargne_5euro].id)
    @epargnes = {
      epargnes_tranquille: a.nil? ? "vide" : a,
      epargnes_normal: b.nil? ? "vide" : b,
      epargnes_ambitieux: c.nil? ? "vide" : c,
      epargnes_1euro: d.nil? ? "vide" : d,
      epargnes_2euro: e.nil? ? "vide" : e,
      epargnes_5euro: f.nil? ? "vide" : f
    }
    @epargne = Epargne.new()
    authorize(@epargne)
  end

  def ssr_pluie
    @user = User.find_by(messenger_id: @user_mi)
    @ssr_user = @user.epargnes
    @ssr = {
      ssr_samedi5: SmartSavingRule.find_by(nom: "météo", mecanisme: "samedi", niveau: "5"),
      ssr_samedi10: SmartSavingRule.find_by(nom: "météo", mecanisme: "samedi", niveau: "10"),
      ssr_samedi15: SmartSavingRule.find_by(nom: "météo", mecanisme: "samedi", niveau: "15"),
      ssr_dimanche5: SmartSavingRule.find_by(nom: "météo", mecanisme: "dimanche", niveau: "5"),
      ssr_dimanche10: SmartSavingRule.find_by(nom: "météo", mecanisme: "dimanche", niveau: "10"),
      ssr_dimanche15: SmartSavingRule.find_by(nom: "météo", mecanisme: "dimanche", niveau: "15")
    }
    a = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_samedi5].id)
    b = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_samedi10].id)
    c = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_samedi15].id)
    d = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_dimanche5].id)
    e = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_dimanche10].id)
    f = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_dimanche15].id)
    @epargnes_s = {
      epargnes_samedi5: a.nil? ? "vide" : a,
      epargnes_samedi10: b.nil? ? "vide" : b,
      epargnes_samedi15: c.nil? ? "vide" : c
    }
    @epargnes_d = {
      epargnes_dimanche5: d.nil? ? "vide" : d,
      epargnes_dimanche10: e.nil? ? "vide" : e,
      epargnes_dimanche15: f.nil? ? "vide" : f
    }
    @epargne = Epargne.new()
    authorize(@epargne)
  end

  def ssr_cigarette
    @user = User.find_by(messenger_id: @user_mi)
    @ssr_user = @user.epargnes
    @ssr = {
      ssr_cigarette1: SmartSavingRule.find_by(nom: "cigarette", mecanisme: "jour", niveau: "1"),
      ssr_cigarette2: SmartSavingRule.find_by(nom: "cigarette", mecanisme: "jour", niveau: "2"),
      ssr_cigarette3: SmartSavingRule.find_by(nom: "cigarette", mecanisme: "jour", niveau: "3")
    }
    a = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_cigarette1].id)
    b = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_cigarette2].id)
    c = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_cigarette3].id)
    @epargnes = {
      epargnes_cigarette1: a.nil? ? "vide" : a,
      epargnes_cigarette2: b.nil? ? "vide" : b,
      epargnes_cigarette3: c.nil? ? "vide" : c
    }
    @epargne = Epargne.new()
    authorize(@epargne)
  end

  def ssr_virement
    @user = User.find_by(messenger_id: @user_mi)
    @ssr_user = @user.epargnes
    @ssr = {
      ssr_pf10: SmartSavingRule.find_by(nom: "virement", mecanisme: "fixe", niveau: "10"),
      ssr_pf20: SmartSavingRule.find_by(nom: "virement", mecanisme: "fixe", niveau: "20"),
      ssr_pv2: SmartSavingRule.find_by(nom: "virement", mecanisme: "pourcentage", niveau: "2"),
      ssr_pv3: SmartSavingRule.find_by(nom: "virement", mecanisme: "pourcentage", niveau: "3"),
      ssr_pv5: SmartSavingRule.find_by(nom: "virement", mecanisme: "pourcentage", niveau: "5")
    }
    a = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_pf10].id)
    b = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_pf20].id)
    c = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_pv2].id)
    d = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_pv3].id)
    e = Epargne.find_by(user_id: @user.id, smart_saving_rule_id: @ssr[:ssr_pv5].id)
    @epargnes = {
      epargnes_pf10: a.nil? ? "vide" : a,
      epargnes_pf20: b.nil? ? "vide" : b,
      epargnes_pv2: c.nil? ? "vide" : c,
      epargnes_pv3: d.nil? ? "vide" : d,
      epargnes_pv5: e.nil? ? "vide" : e
    }
    @epargne = Epargne.new()
    authorize(@epargne)
  end

  def profile
    @user = User.find_by(messenger_id:  @user_mi)
    authorize(@user)
  end

  private

  def find_user
    @user_mi = params["messenger user id"].to_i
  end
end

app/views/webviews/associer_ssr.html.erb
<h1>test</h1>

app/views/webviews/profile.html.erb
<h1>test</h1>

app/views/webviews/show_cagnotte.html.erb
<% if @user_mi == @cagnotte.user.messenger_id %>
  <div class="webview-banner-show-cagnotte">
    <p><em>"<%= @cagnotte.objectif.capitalize %>"</em></p>
    <h2><%= @cagnotte.montant %>€</h2>
  </div>
  <div class="webview-show-cb-picto-box">
    <div class="webview-show-cb-picto">
      <%= image_tag "piggy-bank-solid.png" %>
    </div>
  </div>
  <div class="webview-show-cb-liste-operations">
    <div class="webview-bar-objectif">
      <p><%= @cagnotte.montant %>€ recoltés sur <%= @cagnotte.somme %>€ d'objectif</p>
      <div class="bar">
        <div class="percentage has-tip"  style="width: <%= (@cagnotte.montant/@cagnotte.somme)*100 %>%">
        </div>
      </div>
    </div>
    <hr>
    <% @cagnotte.transactions.order(created_at: :asc).last(15).each do |transaction| %>
      <div class="webview-show-cb-card">
        <div class="row">
          <div class="col-xs-8">
            <div class="webview-show-cb-info-ope">
              <% if transaction.retrait == true %>
                <h4>Retrait</h4>
              <% else %>
                <h4>Épargne <%= (transaction.automatique == true)? "automatique" : "manuelle" %></h4>
              <% end %>
              <p><%= transaction.created_at %></p>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="webview-show-cb-montant-ope">
              <% if transaction.retrait == false %>
                <div class="webview-montant-vert"><p><%= transaction.montant %> €</p></div>
              <% else %>
                <div class="webview-montant-rouge"><p><%= transaction.montant %> €</p></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% else %>
  <div class="webview-banner-show-cb">
    <h2>Error</h2>
  </div>
  <div class="webview-show-cb-liste-operations">
    <p>Vous n'êtes pas authorisé à accéder à ce compte.</p>
  </div>
<% end %>

app/views/webviews/show_cb.html.erb
<% if @user_mi == @cb.user.messenger_id %>
  <div class="webview-banner-show-cb">
    <p><em>Solde du Compte Courant</em></p>
    <h2><%= @cb.solde %>€</h2>
  </div>
  <div class="webview-show-cb-picto-box">
    <div class="webview-show-cb-picto">
      <%= image_tag "university-solid.png" %>
    </div>
  </div>
  <div class="webview-show-cb-liste-operations">
    <% @cb.operations.order(created_at: :asc).last(10).each do |operation| %>
      <div class="webview-show-cb-card">
        <div class="row">
          <div class="col-xs-8">
            <div class="webview-show-cb-info-ope">
              <h4><%= operation.libelle %></h4>
              <p><%= operation.date %></p>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="webview-show-cb-montant-ope">
              <% if operation.montant >= 0 %>
                <div class="webview-montant-vert"><p><%= operation.montant %> €</p></div>
              <% else %>
                <div class="webview-montant-rouge"><p><%= operation.montant %> €</p></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% else %>
  <div class="webview-banner-show-cb">
    <h2>Error</h2>
  </div>
  <div class="webview-show-cb-liste-operations">
    <p>Vous n'êtes pas authorisé à accéder à ce compte.</p>
  </div>
<% end %>

app/views/webviews/ssr_cigarette.html.erb
<div class="webview-banner-show-cb center-flex-box">
  <h2>Gère ta règle 👇</h2>
</div>

<div class="conteneur-webview-depargne">
  <div class="webview-depargne-explications-box">
    <div class="webview-depargne-explications-title">
      <%= image_tag "no-smoking-sign.png" %>
      <div class="webview-depargne-explications-title-text">
        <h3>J'arrête de fumer</h3>
      </div>
    </div>
    <p>Allez ! Tu peux le faire ! Surtout si ca te fait gagner de l’argent non ? Je suis là pour ça.</p>
  </div>

  <hr>
  <h3>Paramètre ta règle</h3>
  <div class="webview-depargne-choix-niveau">
    <div class="webview-depargne-title-et-infos">
      <h3>Chaque jour sans cigarette</h3>
    </div>

    <div class="webview-depargne-choix-niveau-card">
      <div class="webview-depargne-choix-niveau-card-button">
        <% if @ssr_user.include?(@epargnes[:epargnes_cigarette1])%>
          <div class="webview-depargne-position-boutton webview-depargne-position-boutton-on">
            <%= link_to epargne_path(@epargnes[:epargnes_cigarette1]), method: :delete, remote: true do %>
              <div class="base_switch_button">
                <div class="switch_button_element_texte-on">
                  <p>ON</p>
                </div>
                <div class="switch_button_element_blanc"></div>
              </div>
            <% end %>
          </div>
        <% elsif @epargnes.values.uniq.count > 1 %>
          <%= simple_form_for [@epargnes.values.uniq[0] == "vide" ? @epargnes.values.uniq[1] : @epargnes.values.uniq[0]], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette1].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <%= simple_form_for [@epargne], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette1].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="webview-depargne-titre-regle">
        <h4>1€ mis de côté</h4>
      </div>
    </div>

    <div class="webview-depargne-choix-niveau-card">
      <div class="webview-depargne-choix-niveau-card-button">
        <% if @ssr_user.include?(@epargnes[:epargnes_cigarette2])%>
          <div class="webview-depargne-position-boutton webview-depargne-position-boutton-on">
            <%= link_to epargne_path(@epargnes[:epargnes_cigarette2]), method: :delete, remote: true do %>
              <div class="base_switch_button">
                <div class="switch_button_element_texte-on">
                  <p>ON</p>
                </div>
                <div class="switch_button_element_blanc"></div>
              </div>
            <% end %>
          </div>
        <% elsif @epargnes.values.uniq.count > 1 %>
          <%= simple_form_for [@epargnes.values.uniq[0] == "vide" ? @epargnes.values.uniq[1] : @epargnes.values.uniq[0]], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette2].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <%= simple_form_for [@epargne], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette2].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="webview-depargne-titre-regle">
        <h4>2€ mis de côté</h4>
      </div>
    </div>

    <div class="webview-depargne-choix-niveau-card">
      <div class="webview-depargne-choix-niveau-card-button">
        <% if @ssr_user.include?(@epargnes[:epargnes_cigarette3])%>
          <div class="webview-depargne-position-boutton webview-depargne-position-boutton-on">
            <%= link_to epargne_path(@epargnes[:epargnes_cigarette3]), method: :delete, remote: true do %>
              <div class="base_switch_button">
                <div class="switch_button_element_texte-on">
                  <p>ON</p>
                </div>
                <div class="switch_button_element_blanc"></div>
              </div>
            <% end %>
          </div>
        <% elsif @epargnes.values.uniq.count > 1 %>
          <%= simple_form_for [@epargnes.values.uniq[0] == "vide" ? @epargnes.values.uniq[1] : @epargnes.values.uniq[0]], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette3].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <%= simple_form_for [@epargne], remote: true do |f| %>
            <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
            <%= f.input :smart_saving_rule_id, input_html: { id: 'user_id_cagnotte', value: @ssr[:ssr_cigarette3].id }, as: :hidden  %>
             <div class="webview-depargne-position-boutton">
              <%= button_tag(type: 'submit') do %>
                <div class="base_switch_button become-off">
                  <div class="switch_button_element_blanc"></div>
                  <div class="switch_button_element_texte-off">
                    <p>OFF</p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="webview-depargne-titre-regle">
        <h4>3€ mis de côté</h4>
      </div>
    </div>

  </div>


  <div class="position-boutton-valider">
    <a href="#" class="boutton-valider">Valider</a>
  </div>

</div>

app/views/webviews/test.html.erb
<h1>test</h1>
<% @token_list.each do |token| %>
  <%= token[0] %>
<% end %>