config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users, controllers: {
           :sessions => "users/sessions",
           :registrations => "users/registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'token_already_used', to: 'pages#token_already_used'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'relevedecomptes', to: 'chatfuels#relevedecomptes'
      get 'gestioncagnottes', to: 'chatfuels#gestioncagnottes'
      get 'gestiondepargne', to: 'chatfuels#gestiondepargne'
      get 'gestionssr', to: 'chatfuels#gestionssr'
      get 'menuquickreplies', to: 'chatfuels#menuquickreplies'
      get 'redirecttomenu', to: 'chatfuels#redirecttomenu'
      get 'veriftoken', to: 'chatfuels#veriftoken'
      get 'parametres', to: 'chatfuels#parametres'
      get 'gestionpause', to: 'chatfuels#gestionpause'
      resources :leads, only: [:create]
    end
  end

  get 'show_cb', to: 'webviews#show_cb'
  get 'show_cagnotte', to: 'webviews#show_cagnotte'
  get 'ma_depargne', to: 'webviews#ma_depargne'
  get 'ssr_pluie', to: 'webviews#ssr_pluie'
  get 'ssr_cigarette', to: 'webviews#ssr_cigarette'
  get 'ssr_virement', to: 'webviews#ssr_virement'
  get 'associer_ssr', to: 'webviews#associer_ssr'
  get 'pre_created', to: 'pages#pre_created'
  get 'profile', to: 'webviews#profile'
  get 'connected_account', to: 'pages#connected_account'

  namespace :budgea, defaults: { format: :json } do
    post 'synchronized_data', to: 'webhooks#synchronized_data'
    post 'daily_update_data', to: 'webhooks#daily_update_data'
  end


  resources :cagnottes, only: [ :new, :create, :edit, :update, :destroy ]
  resources :epargnes
end

app/models/cagnotte.rb
class Cagnotte < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :objectif, presence: true
  validates :genre, presence: true
  validates :somme, presence: true
end

app/controllers/api/v1/cagnottes_controller.rb
class Api::V1::CagnottesController < Api::V1::BaseController
  before_action :set_cagnotte, only: [ :show, :update ]

  def index
    user = User.where(messenger_id: params["messenger user id"])
    @cagnottes = policy_scope(Cagnotte).where(user: user)
    @cb = CompteBancaire.where(user: user)
    @montant = 0
    @cagnottes.each do |cagnotte|
      @montant = @montant + cagnotte.montant
    end
  end

  def show
  end

  def update
    if @cagnotte.update(cagnotte_params)
      render :show
    else
      render_error
    end
  end

  def create
    @cagnotte = current_user.cagnottes.build(

      )
    authorize @cagnotte
    if @cagnotte.save
      render :show
    else
      render_error
    end
  end

  private

  def set_cagnotte
    @cagnotte = Cagnotte.find(params[:id])
    authorize @cagnotte # For Pundit
  end

  def cagnotte_params
    params.require(:cagnotte).permit(:genre, :date, :montant, :objectif)
  end

  def render_error
    render json: { errors: @cagnotte.errors.full_messages },
      status: :unprocessable_entity
  end
end

app/controllers/cagnottes_controller.rb
class CagnottesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_cagnotte, only: [:edit, :update, :destroy]

  def new
    @user = User.find_by(messenger_id: params["messenger user id"].to_i)
    @cagnotte = Cagnotte.new
    authorize(@cagnotte)
  end

  def create
    @cagnotte = Cagnotte.new(cagnotte_params)
    @cagnotte.montant = 0
    @cagnotte.genre = "objectif"
    user = User.find(@cagnotte.user_id)
    authorize(@cagnotte)

    if @cagnotte.save
      if Rails.env == "development"
        redirect_to "http://localhost:3000/show_cagnotte?cagnotte_id=#{@cagnotte.id} &messenger user id=#{user.messenger_id}"
      else
        redirect_to "https://www.ledepargneur.fr/show_cagnotte?cagnotte_id=#{@cagnotte.id} &messenger user id=#{user.messenger_id}"
      end
    else
      if Rails.env == "development"
        redirect_to "http://localhost:3000/cagnottes/new?messenger user id=#{user.messenger_id}"
      else
        redirect_to "https://www.ledepargneur.fr/cagnottes/new?messenger user id=#{user.messenger_id}"
      end
    end
  end

  def edit
  end

  def update
    user = User.find(@cagnotte.user_id)
    authorize(@cagnotte)

    if @cagnotte.update(cagnotte_params)
      if Rails.env == "development"
        redirect_to "http://localhost:3000/show_cagnotte?cagnotte_id=#{@cagnotte.id} &messenger user id=#{user.messenger_id}"
      else
        redirect_to "https://www.ledepargneur.fr/show_cagnotte?cagnotte_id=#{@cagnotte.id} &messenger user id=#{user.messenger_id}"
      end
    else
      if Rails.env == "development"
        redirect_to "http://localhost:3000/cagnottes/edit?messenger user id=#{user.messenger_id}"
      else
        redirect_to "https://www.ledepargneur.fr/cagnottes/edit?messenger user id=#{user.messenger_id}"
      end
    end
  end

  def destroy
    user = User.find(@cagnotte.user_id)
    montant = @cagnotte.montant
    precaution = Cagnotte.find_by(user_id: user.id, objectif: "precaution")
    precaution.montant += montant
    precaution.save!
    @cagnotte.destroy
    if Rails.env == "development"
      redirect_to "http://localhost:3000/cagnottes/new?messenger user id=#{user.messenger_id}"
    else
      redirect_to "https://www.ledepargneur.fr/cagnottes/new?messenger user id=#{user.messenger_id}"
    end
  end

  private

  def find_cagnotte
    @cagnotte = Cagnotte.find(params[:id])
    authorize(@cagnotte)
  end

  def cagnotte_params
    params.require(:cagnotte).permit(:date, :objectif, :somme, :user_id)
  end
end

app/views/cagnottes/edit.html.erb
<div class="webview-banner-new-cagnotte">
  <div class="conteneur-new-cagnotte">
    <p></p>
    <p></p>
    <h2>Un ajustement à faire ?</h2>
  </div>
</div>

<div class="webview-show-cb-picto-box">
  <div class="webview-show-cb-picto">
    <%= image_tag "piggy-bank-solid.png" %>
  </div>
</div>

<div class="conteneur-new-cagnotte">
  <h3>Modfier ma cagnotte</h3>
  <div class="webview-form-new-cagnotte">
    <%= simple_form_for [@cagnotte] do |f| %>
      <%= f.input :user_id, as: :hidden %>
      <%= f.input :objectif, require: true %>
      <%= f.input :date, as: :date, start_year: Date.today.year,
                        end_year: Date.today.year + 10,
                        order: [:day, :month, :year] %>
      <%= f.input :somme, require: true %>
      <div class="centered-element">
        <%= f.submit 'Modifier ma cagnotte', class: "boutton-submit-webview" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cagnottes/new.html.erb
<% if @user.cagnottes.count < 2 %>
  <div class="webview-banner-new-cagnotte">
    <div class="conteneur-new-cagnotte">
      <p>Pour des vacances, un téléphone, ou un cadeau...</p>
      <h2>Créez votre Cagnotte !</h2>
    </div>
  </div>

  <div class="webview-show-cb-picto-box">
    <div class="webview-show-cb-picto">
      <%= image_tag "piggy-bank-solid.png" %>
    </div>
  </div>

  <div class="webview-explication-cagnottes">
    <div class="conteneur-new-cagnotte">
      <h3>Pourquoi créer ma cagnotte ?</h3>
      <div class="row">
        <div class="col-xs-12">
          <div class="webview-card-cagnottes">
            <div class="row">
              <div class="col-xs-3"><%= image_tag "cellphone.svg", class: "picto-cagnottes" %></div>
              <div class="col-xs-9">
                <p>Sois MALIN: fixe toi un objectif concret et daté</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="webview-card-cagnottes">
            <div class="row">
              <div class="col-xs-3"><%= image_tag "money.svg", class: "picto-cagnottes" %></div>
              <div class="col-xs-9">
                <p>Remplis ta cagnotte grâce à ta dépargne</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="webview-card-cagnottes">
            <div class="row">
              <div class="col-xs-3"><%= image_tag "success.svg", class: "picto-cagnottes" %></div>
              <div class="col-xs-9">
                <p>Victoire ! <br>Tu t'es fait un kiff 😎</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="conteneur-new-cagnotte">
    <h3>Je crée ma cagnotte</h3>
    <div class="webview-form-new-cagnotte">
      <%= simple_form_for [@cagnotte] do |f| %>
        <%= f.input :user_id, input_html: { id: 'user_id_cagnotte', value: @user.id }, as: :hidden %>
        <%= f.input :objectif, require: true %>
        <%= f.input :date, as: :date, start_year: Date.today.year,
                                end_year: Date.today.year + 10,
                                order: [:day, :month, :year] %>
        <%= f.input :somme, require: true %>
        <div class="centered-element">
          <%= f.submit 'Créer ma cagnotte', class: "boutton-submit-webview" %>
        </div>
      <% end %>
    </div>
  </div>



<% else %>


  <div class="webview-banner-new-cagnotte">
    <div class="conteneur-new-cagnotte">
      <h3>Oups...</h3>
      <p>Vous ne pouvez pour l'instant pas créer plus d'une cagnotte à la fois</p>
    </div>
  </div>

  <div class="conteneur-new-cagnotte">
    <% @user.cagnottes.where(genre: "objectif").each do |cagnotte| %>
      <h4><%= cagnotte.objectif.capitalize %></h4>
      <div class="bar">
        <div class="percentage has-tip"  style="width: <%= (cagnotte.montant/cagnotte.somme)*100 %>%">
        </div>
      </div>
      <p><%= cagnotte.montant %>€ recoltés sur <%= cagnotte.somme %>€ d'objectif</p>
      <p><%= cagnotte.date unless cagnotte.date.nil? %></p>
      <%= link_to 'Modifier', edit_cagnotte_path(cagnotte), class: "btn-gris-sobre" %>
      |
      <%= link_to 'Supprimer', cagnotte_path(cagnotte), method: :delete, data: { confirm: 'Tu es sûr de vouloir supprimer définitivement cette cagnotte ? L\'argent contenu sera transféré sur ta cagnotte de précaution ' }, class: "btn-gris-sobre" %>
    <% end %>
  </div>

<% end %>